//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace IssueTracker.Web.Models
{
    public partial class ViewModelThreadAttachment
    {
        public int Id { get; set; }
        public int ThreadId { get; set; }
        public int AttachmentId { get; set; }
    
        public virtual ViewModelAttachment ViewModelAttachment { get; set; }
        public virtual ViewModelThread ViewModelThread { get; set; }
    }
}
