//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace IssueTracker.Web.Models
{
    public partial class ViewModelAttachment
    {
        public ViewModelAttachment()
        {
            this.ViewModelMessageAttachment = new HashSet<ViewModelMessageAttachment>();
            this.ViewModelThreadAttachment = new HashSet<ViewModelThreadAttachment>();
        }
    
        public int Id { get; set; }
        public string OriginalTitle { get; set; }
        public string GUID { get; set; }
        public byte[] AttachmentBinary { get; set; }
    
        public virtual ICollection<ViewModelMessageAttachment> ViewModelMessageAttachment { get; set; }
        public virtual ICollection<ViewModelThreadAttachment> ViewModelThreadAttachment { get; set; }
    }
}
