//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTracker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public Attachment()
        {
            this.MessageAttachment = new HashSet<MessageAttachment>();
            this.ThreadAttachment = new HashSet<ThreadAttachment>();
        }
    
        public int Id { get; set; }
        public string OriginalTitle { get; set; }
        public string GUID { get; set; }
        public byte[] AttachmentBinary { get; set; }
    
        public virtual ICollection<MessageAttachment> MessageAttachment { get; set; }
        public virtual ICollection<ThreadAttachment> ThreadAttachment { get; set; }
    }
}
