//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTracker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Message = new HashSet<Message>();
            this.ThreadAttachment = new HashSet<ThreadAttachment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int LastModBy { get; set; }
        public System.DateTime LastModDate { get; set; }
    
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<ThreadAttachment> ThreadAttachment { get; set; }
    }
}
